"""
Notes data for Excel output sheets - contains unit explanations and descriptions
for all output metrics in the steel industry decarbonization optimization model.
"""

def get_notes_data_v2():
    """
    Get notes data for main_v2.py (uses annualized CAPEX approach)
    Returns list of lists for Excel notes sheet
    """
    return [
        ['Sheet Name', 'Column/Metric', 'Unit', 'Description'],
        ['Global Annual Summary', 'Year', 'Calendar year', 'Analysis year'],
        ['Global Annual Summary', 'Total CAPEX', 'KRW', 'Total capital expenditures across all systems'],
        ['Global Annual Summary', 'Total Renewal Cost', 'KRW', 'Total technology renewal costs across all systems'],
        ['Global Annual Summary', 'Total OPEX', 'KRW', 'Total operating expenditures across all systems'],
        ['Global Annual Summary', 'Total Cost', 'KRW', 'Sum of CAPEX + Renewal Cost + OPEX'],
        ['Global Annual Summary', 'Total Emissions', 'tCO2e/year', 'Total greenhouse gas emissions across all systems'],
        ['Global Annual Summary', 'Fuel Consumption (Coal_BB)', 'GJ/year', 'Annual coal consumption (blast furnace basic)'],
        ['Global Annual Summary', 'Fuel Consumption (BF gas_BB)', 'GJ/year', 'Annual blast furnace gas consumption (basic)'],
        ['Global Annual Summary', 'Fuel Consumption (COG_BB)', 'GJ/year', 'Annual coke oven gas consumption (basic)'],
        ['Global Annual Summary', 'Fuel Consumption (BOF gas_BB)', 'GJ/year', 'Annual basic oxygen furnace gas consumption (basic)'],
        ['Global Annual Summary', 'Fuel Consumption (Natural gas_BX)', 'GJ/year', 'Annual natural gas consumption (BOF extension)'],
        ['Global Annual Summary', 'Fuel Consumption (Hydrogen_H2)', 'GJ/year', 'Annual hydrogen consumption (H2-DRI)'],
        ['Global Annual Summary', 'Fuel Consumption (Electricity_H2)', 'GJ/year', 'Annual electricity consumption (H2-DRI)'],
        ['Global Annual Summary', 'Fuel Consumption (Electricity_EAF)', 'GJ/year', 'Annual electricity consumption (EAF)'],
        ['Global Annual Summary', 'Feedstock Consumption (Iron ore_BB)', 'tons/year', 'Annual iron ore consumption (blast furnace basic)'],
        ['Global Annual Summary', 'Feedstock Consumption (Scrap_BB)', 'tons/year', 'Annual steel scrap consumption (blast furnace basic)'],
        ['Global Annual Summary', 'Feedstock Consumption (HBI_BB)', 'tons/year', 'Annual hot briquetted iron consumption (basic)'],
        ['Global Annual Summary', 'Feedstock Consumption (Iron ore_BX)', 'tons/year', 'Annual iron ore consumption (BOF extension)'],
        ['Global Annual Summary', 'Feedstock Consumption (Iron ore_H2)', 'tons/year', 'Annual iron ore consumption (H2-DRI)'],
        ['Global Annual Summary', 'Feedstock Consumption (Scrap_H2)', 'tons/year', 'Annual steel scrap consumption (H2-DRI)'],
        ['Global Annual Summary', 'Feedstock Consumption (Scrap_EAF)', 'tons/year', 'Annual steel scrap consumption (EAF)'],
        ['Global Annual Summary', 'Feedstock Consumption (HBI_EAF)', 'tons/year', 'Annual hot briquetted iron consumption (EAF)'],
        ['Global Annual Summary', 'Tech Adoption (BF-BOF)', 'count', 'Number of systems using blast furnace - basic oxygen furnace'],
        ['Global Annual Summary', 'Tech Adoption (BF-BOF-FX)', 'count', 'Number of systems using BF-BOF with flux optimization'],
        ['Global Annual Summary', 'Tech Adoption (H2-DRI-ESF)', 'count', 'Number of systems using hydrogen direct reduced iron + electric steelmaking furnace'],
        ['Global Annual Summary', 'Tech Adoption (EAF)', 'count', 'Number of systems using electric arc furnace'],
        ['', '', '', ''],
        ['Discounted Costs', 'Discounted Annualized CAPEX', 'KRW', 'Present value of annualized capital expenditures (2% discount rate)'],
        ['Discounted Costs', 'Discounted OPEX', 'KRW', 'Present value of operating expenditures (2% discount rate)'],
        ['Discounted Costs', 'Discounted Fuel Cost', 'KRW', 'Present value of fuel costs (2% discount rate)'],
        ['Discounted Costs', 'Discounted Feedstock Cost', 'KRW', 'Present value of feedstock costs (2% discount rate)'],
        ['Discounted Costs', 'Total Discounted Cost', 'KRW', 'Sum of all discounted costs'],
        ['Discounted Costs', 'Discounted Cost per Ton', 'KRW/ton', 'Discounted cost per unit of steel production'],
        ['Discounted Costs', 'Emission Reduction', 'tCO2e', 'Annual emission reduction from baseline'],
        ['Discounted Costs', 'Cumulative Discounted Cost', 'KRW', 'Cumulative present value of all costs'],
        ['Discounted Costs', 'Cumulative Emission Reduction', 'tCO2e', 'Cumulative emission reduction from baseline'],
        ['Discounted Costs', 'Marginal Abatement Cost (MAC)', 'KRW/tCO2e', 'Cost per unit of emission reduction'],
        ['', '', '', ''],
        ['Unit Costs and MAC', 'Unit CAPEX', 'KRW/ton', 'Capital expenditure per unit of steel production'],
        ['Unit Costs and MAC', 'Unit Renewal', 'KRW/ton', 'Renewal cost per unit of steel production'],
        ['Unit Costs and MAC', 'Unit OPEX', 'KRW/ton', 'Operating expenditure per unit of steel production'],
        ['Unit Costs and MAC', 'Unit Fuel Cost', 'KRW/ton', 'Fuel cost per unit of steel production'],
        ['Unit Costs and MAC', 'Unit Feedstock Cost', 'KRW/ton', 'Feedstock cost per unit of steel production'],
        ['Unit Costs and MAC', 'Unit Annualized CAPEX', 'KRW/ton', 'Annualized CAPEX per unit of steel production'],
        ['Unit Costs and MAC', 'Total Unit Cost', 'KRW/ton', 'Total cost per unit of steel production'],
        ['Unit Costs and MAC', 'Emissions Intensity', 'tCO2e/ton', 'Emissions per unit of steel production'],
        ['', '', '', ''],
        ['Annualized CAPEX', 'Global Annualized CAPEX', 'KRW/year', 'Total annualized capital expenditures across all systems'],
        ['Annualized CAPEX', '{System} Annualized CAPEX', 'KRW/year', 'Annualized capital expenditures by system'],
        ['', '', '', ''],
        ['System CAPEX', '{System}', 'KRW', 'Annual capital expenditures by system'],
        ['', '', '', ''],
        ['Technology Production Share', 'Total Production', 'tons/year', 'Total steel production across all systems'],
        ['Technology Production Share', '{Tech} Production', 'tons/year', 'Steel production by technology'],
        ['Technology Production Share', '{Tech} Share (%)', '%', 'Technology share of total production'],
        ['', '', '', ''],
        ['System Sheets', 'CAPEX', 'KRW', 'Annual capital expenditures for the system'],
        ['System Sheets', 'Renewal Cost', 'KRW', 'Annual renewal costs for the system'],
        ['System Sheets', 'OPEX', 'KRW', 'Annual operating expenditures for the system'],
        ['System Sheets', 'Total Emissions', 'tCO2e', 'Annual emissions for the system'],
        ['System Sheets', 'Fuel consumption columns', 'GJ/year', 'Annual fuel consumption by fuel type'],
        ['System Sheets', 'Feedstock consumption columns', 'tons/year', 'Annual feedstock consumption by feedstock type'],
        ['System Sheets', 'Technology Status (Active)', '0/1', 'Binary indicator if technology is active'],
        ['System Sheets', 'Technology Status (Continue)', '0/1', 'Binary indicator if technology continues'],
        ['System Sheets', 'Technology Status (Replace)', '0/1', 'Binary indicator if technology is replaced'],
        ['System Sheets', 'Technology Status (Renew)', '0/1', 'Binary indicator if technology is renewed'],
        ['System Sheets', 'Production', 'tons/year', 'Annual steel production by technology'],
        ['', '', '', ''],
        ['General Notes', '', '', ''],
        ['Currency', 'All costs are in Korean Won (KRW)', '', ''],
        ['Energy', 'All fuel consumptions are in Gigajoules (GJ)', '', ''],
        ['Mass', 'All feedstock/production quantities are in metric tons', '', ''],
        ['Emissions', 'All emissions are in metric tons CO2 equivalent (tCO2e)', '', ''],
        ['Discount Rate', 'Applied 2% annual discount rate for cost calculations', '', ''],
        ['Technology Codes', 'BF-BOF: Blast Furnace - Basic Oxygen Furnace', '', ''],
        ['Technology Codes', 'BF-BOF-FX: BF-BOF with Flux Optimization', '', ''],
        ['Technology Codes', 'H2-DRI-ESF: Hydrogen Direct Reduced Iron + Electric Steelmaking Furnace', '', ''],
        ['Technology Codes', 'EAF: Electric Arc Furnace', '', ''],
        ['Fuel Codes', '_BB: Basic Blast Furnace route', '', ''],
        ['Fuel Codes', '_BX: BOF Extension route', '', ''],
        ['Fuel Codes', '_H2: Hydrogen-based route', '', ''],
        ['Fuel Codes', '_EAF: Electric Arc Furnace route', '', ''],
    ]

def get_notes_data_v1():
    """
    Get notes data for main.py (uses separate CAPEX and renewal costs)
    Returns list of lists for Excel notes sheet
    """
    return [
        ['Sheet Name', 'Column/Metric', 'Unit', 'Description'],
        ['Global Annual Summary', 'Year', 'Calendar year', 'Analysis year'],
        ['Global Annual Summary', 'Total CAPEX', 'KRW', 'Total capital expenditures across all systems'],
        ['Global Annual Summary', 'Total Renewal Cost', 'KRW', 'Total technology renewal costs across all systems'],
        ['Global Annual Summary', 'Total OPEX', 'KRW', 'Total operating expenditures across all systems'],
        ['Global Annual Summary', 'Total Cost', 'KRW', 'Sum of CAPEX + Renewal Cost + OPEX'],
        ['Global Annual Summary', 'Total Emissions', 'tCO2e/year', 'Total greenhouse gas emissions across all systems'],
        ['Global Annual Summary', 'Fuel Consumption (Coal_BB)', 'GJ/year', 'Annual coal consumption (blast furnace basic)'],
        ['Global Annual Summary', 'Fuel Consumption (BF gas_BB)', 'GJ/year', 'Annual blast furnace gas consumption (basic)'],
        ['Global Annual Summary', 'Fuel Consumption (COG_BB)', 'GJ/year', 'Annual coke oven gas consumption (basic)'],
        ['Global Annual Summary', 'Fuel Consumption (BOF gas_BB)', 'GJ/year', 'Annual basic oxygen furnace gas consumption (basic)'],
        ['Global Annual Summary', 'Fuel Consumption (Natural gas_BX)', 'GJ/year', 'Annual natural gas consumption (BOF extension)'],
        ['Global Annual Summary', 'Fuel Consumption (Hydrogen_H2)', 'GJ/year', 'Annual hydrogen consumption (H2-DRI)'],
        ['Global Annual Summary', 'Fuel Consumption (Electricity_H2)', 'GJ/year', 'Annual electricity consumption (H2-DRI)'],
        ['Global Annual Summary', 'Fuel Consumption (Electricity_EAF)', 'GJ/year', 'Annual electricity consumption (EAF)'],
        ['Global Annual Summary', 'Feedstock Consumption (Iron ore_BB)', 'tons/year', 'Annual iron ore consumption (blast furnace basic)'],
        ['Global Annual Summary', 'Feedstock Consumption (Scrap_BB)', 'tons/year', 'Annual steel scrap consumption (blast furnace basic)'],
        ['Global Annual Summary', 'Feedstock Consumption (HBI_BB)', 'tons/year', 'Annual hot briquetted iron consumption (basic)'],
        ['Global Annual Summary', 'Feedstock Consumption (Iron ore_BX)', 'tons/year', 'Annual iron ore consumption (BOF extension)'],
        ['Global Annual Summary', 'Feedstock Consumption (Iron ore_H2)', 'tons/year', 'Annual iron ore consumption (H2-DRI)'],
        ['Global Annual Summary', 'Feedstock Consumption (Scrap_H2)', 'tons/year', 'Annual steel scrap consumption (H2-DRI)'],
        ['Global Annual Summary', 'Feedstock Consumption (Scrap_EAF)', 'tons/year', 'Annual steel scrap consumption (EAF)'],
        ['Global Annual Summary', 'Feedstock Consumption (HBI_EAF)', 'tons/year', 'Annual hot briquetted iron consumption (EAF)'],
        ['Global Annual Summary', 'Tech Adoption (BF-BOF)', 'count', 'Number of systems using blast furnace - basic oxygen furnace'],
        ['Global Annual Summary', 'Tech Adoption (BF-BOF-FX)', 'count', 'Number of systems using BF-BOF with flux optimization'],
        ['Global Annual Summary', 'Tech Adoption (H2-DRI-ESF)', 'count', 'Number of systems using hydrogen direct reduced iron + electric steelmaking furnace'],
        ['Global Annual Summary', 'Tech Adoption (EAF)', 'count', 'Number of systems using electric arc furnace'],
        ['', '', '', ''],
        ['Discounted Costs', 'Discounted CAPEX', 'KRW', 'Present value of capital expenditures (2% discount rate)'],
        ['Discounted Costs', 'Discounted Renewal', 'KRW', 'Present value of renewal costs (2% discount rate)'],
        ['Discounted Costs', 'Discounted OPEX', 'KRW', 'Present value of operating expenditures (2% discount rate)'],
        ['Discounted Costs', 'Discounted Fuel Cost', 'KRW', 'Present value of fuel costs (2% discount rate)'],
        ['Discounted Costs', 'Discounted Feedstock Cost', 'KRW', 'Present value of feedstock costs (2% discount rate)'],
        ['Discounted Costs', 'Total Discounted Cost', 'KRW', 'Sum of all discounted costs'],
        ['Discounted Costs', 'Emission Reduction', 'tCO2e', 'Annual emission reduction from baseline'],
        ['Discounted Costs', 'Cumulative Discounted Cost', 'KRW', 'Cumulative present value of all costs'],
        ['Discounted Costs', 'Cumulative Emission Reduction', 'tCO2e', 'Cumulative emission reduction from baseline'],
        ['Discounted Costs', 'Marginal Abatement Cost (MAC)', 'KRW/tCO2e', 'Cost per unit of emission reduction'],
        ['', '', '', ''],
        ['Unit Costs and MAC', 'Unit CAPEX', 'KRW/ton', 'Capital expenditure per unit of steel production'],
        ['Unit Costs and MAC', 'Unit Renewal', 'KRW/ton', 'Renewal cost per unit of steel production'],
        ['Unit Costs and MAC', 'Unit OPEX', 'KRW/ton', 'Operating expenditure per unit of steel production'],
        ['Unit Costs and MAC', 'Unit Fuel Cost', 'KRW/ton', 'Fuel cost per unit of steel production'],
        ['Unit Costs and MAC', 'Unit Feedstock Cost', 'KRW/ton', 'Feedstock cost per unit of steel production'],
        ['Unit Costs and MAC', 'Unit Annualized CAPEX', 'KRW/ton', 'Annualized CAPEX per unit of steel production'],
        ['Unit Costs and MAC', 'Total Unit Cost', 'KRW/ton', 'Total cost per unit of steel production'],
        ['Unit Costs and MAC', 'Emissions Intensity', 'tCO2e/ton', 'Emissions per unit of steel production'],
        ['', '', '', ''],
        ['Annualized CAPEX', 'Global Annualized CAPEX', 'KRW/year', 'Total annualized capital expenditures across all systems'],
        ['Annualized CAPEX', '{System} Annualized CAPEX', 'KRW/year', 'Annualized capital expenditures by system'],
        ['', '', '', ''],
        ['System CAPEX', '{System}', 'KRW', 'Annual capital expenditures by system'],
        ['', '', '', ''],
        ['Technology Production Share', 'Total Production', 'tons/year', 'Total steel production across all systems'],
        ['Technology Production Share', '{Tech} Production', 'tons/year', 'Steel production by technology'],
        ['Technology Production Share', '{Tech} Share (%)', '%', 'Technology share of total production'],
        ['', '', '', ''],
        ['System Sheets', 'CAPEX', 'KRW', 'Annual capital expenditures for the system'],
        ['System Sheets', 'Renewal Cost', 'KRW', 'Annual renewal costs for the system'],
        ['System Sheets', 'OPEX', 'KRW', 'Annual operating expenditures for the system'],
        ['System Sheets', 'Total Emissions', 'tCO2e', 'Annual emissions for the system'],
        ['System Sheets', 'Fuel consumption columns', 'GJ/year', 'Annual fuel consumption by fuel type'],
        ['System Sheets', 'Feedstock consumption columns', 'tons/year', 'Annual feedstock consumption by feedstock type'],
        ['System Sheets', 'Technology Status (Active)', '0/1', 'Binary indicator if technology is active'],
        ['System Sheets', 'Technology Status (Continue)', '0/1', 'Binary indicator if technology continues'],
        ['System Sheets', 'Technology Status (Replace)', '0/1', 'Binary indicator if technology is replaced'],
        ['System Sheets', 'Technology Status (Renew)', '0/1', 'Binary indicator if technology is renewed'],
        ['System Sheets', 'Production', 'tons/year', 'Annual steel production by technology'],
        ['', '', '', ''],
        ['General Notes', '', '', ''],
        ['Currency', 'All costs are in Korean Won (KRW)', '', ''],
        ['Energy', 'All fuel consumptions are in Gigajoules (GJ)', '', ''],
        ['Mass', 'All feedstock/production quantities are in metric tons', '', ''],
        ['Emissions', 'All emissions are in metric tons CO2 equivalent (tCO2e)', '', ''],
        ['Discount Rate', 'Applied 2% annual discount rate for cost calculations', '', ''],
        ['Technology Codes', 'BF-BOF: Blast Furnace - Basic Oxygen Furnace', '', ''],
        ['Technology Codes', 'BF-BOF-FX: BF-BOF with Flux Optimization', '', ''],
        ['Technology Codes', 'H2-DRI-ESF: Hydrogen Direct Reduced Iron + Electric Steelmaking Furnace', '', ''],
        ['Technology Codes', 'EAF: Electric Arc Furnace', '', ''],
        ['Fuel Codes', '_BB: Basic Blast Furnace route', '', ''],
        ['Fuel Codes', '_BX: BOF Extension route', '', ''],
        ['Fuel Codes', '_H2: Hydrogen-based route', '', ''],
        ['Fuel Codes', '_EAF: Electric Arc Furnace route', '', ''],
    ]